### ISSUE TITLE
jest-allure not working with testRunner jest-circus

### ISSUE THREAD

**Issue by gaaliche** [zaqqaz/jest-allure#16]
Hi all,
I'm having the following issue
` FAIL  __tests__/production.test.js
  ● Test suite failed to run

    ReferenceError: jasmine is not defined

    > 1 | import "jest-allure/dist/setup";
        | ^
      2 | 

      at registerAllureReporter (node_modules/jest-allure/dist/setup.js:46:5)
      at Object.<anonymous> (node_modules/jest-allure/dist/setup.js:49:1)
      at Object.<anonymous> (jasmine.config.js:1:1)
          at Array.forEach (<anonymous>)`
Is it mandatory to use the default testRunner `jasmine2` to be able to use this reporter?

**Comment by test-pilott** [comment]
Is there a plan to fix the integration with **jest-circus**?

**Comment by andreabisello** [comment]
same issue here.

**Comment by 4ekki** [comment]
https://www.npmjs.com/package/allure-jest-circus - I used this lib to launch allure reports on top of jest-circus results. However, I'm not sure if it supports everything else, like steps annotations.

**Comment by olexandr13** [comment]
+1
actual for me

**Comment by zaqqaz** [comment]
Sorry I don't have enough time to create PR to support jest-circus, so the only option is to switch to jasmine https://github.com/zaqqaz/jest-allure#uses-jest-circus-or-jest--v-27- 

But I'm happy to review PR if any to support this feature

**Comment by andreabisello** [comment]
@zaqqaz  thanks for your suggestion. i use jest-circus because i need to use jest-retry
https://github.com/facebook/jest/blob/f45d1c939cbf55a71dbfdfc316d2be62b590197f/docs/JestObjectAPI.md#jestretrytimes
i know test should not have needs to retry,
but in my case, i must to do it.
maybe i will find some other plugins to retry failed tests.

**Comment by waynevanson** [comment]
I wouldn't mind giving this a crack.

All the logic inside `src/setup` needs to be adapted to `src/index.ts`, is that correct?

**Comment by morsa1** [comment]
any news about use allure with jest-circus?

**Comment by streLer** [comment]
any news about Jest-Circus support?
