### ISSUE TITLE
[Bug] java.lang.UnsupportedOperationException: The BROWSE action is not supported

### ISSUE THREAD

**Issue by Mariodandre** [zaqqaz/jest-allure#63]
Hello

I installed jest-allure and got the error with allure serve :

```
Exception in thread "main" java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
	at java.desktop/java.awt.Desktop.browse(Desktop.java:524)
	at io.qameta.allure.Commands.openBrowser(Commands.java:228)
	at io.qameta.allure.Commands.open(Commands.java:153)
	at io.qameta.allure.Commands.serve(Commands.java:137)
	at io.qameta.allure.CommandLine.run(CommandLine.java:159)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at io.qameta.allure.CommandLine.main(CommandLine.java:88)
```

I am on Ubutu 18.04.3 LTS (x86-64)

**Comment by zaqqaz** [comment]
Java issue seems to be related to allure itself, not jest-allure (as it's java-free project).
