### ISSUE TITLE
jasmine is not defined after update to jest@27.0.3

### ISSUE THREAD

**Issue by alexneo2003** [zaqqaz/jest-allure#77]
After update jest to latest version 27.0.3 i'm have next error
```javascript
Test suite failed to run

    ReferenceError: jasmine is not defined

    at registerAllureReporter (node_modules/jest-allure/dist/setup.js:62:5)
    at Object.<anonymous> (node_modules/jest-allure/dist/setup.js:65:1)
```
```javascript
jest.config.js

module.exports = {
    reporters: ["default", "jest-allure"],
    setupFilesAfterEnv: ["jest-allure/dist/setup"]
};
```

**Comment by zaqqaz** [comment]
Yep
https://github.com/zaqqaz/jest-allure/blob/master/readme.md#uses-jest-circus-or-jest--v-27-
