### ISSUE TITLE
Running setup throws `ReferenceError: jasmine is not defined` on Jest 27

### ISSUE THREAD

**Issue by pavloconuve** [zaqqaz/jest-allure#80]
Since Jest 27 [switched default test runner](https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults), running setup throws:
```
ReferenceError: jasmine is not defined

  at registerAllureReporter (../../node_modules/jest-allure/dist/setup.js:62:5)
  at Object.<anonymous> (../../node_modules/jest-allure/dist/setup.js:65:1)
```
---
A workaround on this is to add the following to `jest.config.js`:
```
testRunner: "jest-jasmine2"
```

**Comment by serhat-onedio** [comment]
although  this is a fix, I think with this we loose the benefits of jest-circus like retry

**Comment by c4lifa** [comment]
Try this - https://github.com/c4lifa/jest-allure-circus
